export type Film = {
  id: number,
  name: string,
  genre: string,
  date: string,
  posterImage: string,
  backgroundImage: string,
  backgroundColor: string,
  videoLink:string,
  description: string,
  time: number,
  rating: number,
  reviewsCount: number,
  director: string,
  starring: string[],
}